
import type { Metadata } from "next";
import { GeistSans, GeistMono } from 'geist/font';
import { Providers } from "@/components/providers"
import '@repo/ui/globals.css';
import QueryProvider from "@/components/providers/query-provider";

import './globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <Providers>
          <QueryProvider>
            {children}
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}